-- 한줄 주석

/*
    여러줄 주석
    뭐라 적을까나
*/

-- 사용자 계정 생성
-- CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##KH IDENTIFIED BY KH;

-- 권한부여
GRANT CONNECT, RESOURCE TO C##KH;

GRANT CREATE VIEW TO C##KH;

-- 유저 정보 변경 - 테이블스페이스 권한 수정
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##TEST_USER01 IDENTIFIED BY TEAMTEST;
GRANT CONNECT, RESOURCE TO C##TEST_USER01;
ALTER USER C##TEST_USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##TEST_USER02 IDENTIFIED BY TEAMTEST;
GRANT CONNECT, RESOURCE TO C##TEST_USER02;
ALTER USER C##TEST_USER02 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##TEAM2 IDENTIFIED BY TEAM2;
GRANT CONNECT, RESOURCE TO C##TEAM2;
ALTER USER C##TEAM2 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##SEMIPRJTEAM2 IDENTIFIED BY TEAM2;
GRANT CONNECT, RESOURCE TO C##SEMIPRJTEAM2;
ALTER USER C##SEMIPRJTEAM2 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;