-- 감독

CREATE SEQUENCE DIRECTOR_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCYCLE
;

INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '봉준호');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '제임스 카메론');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '신카이 마코토');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '페이턴 리드');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '조지프 코신스키');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '앤드류 리나레스');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '라지쿠마르 히라니');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '저우제룬');
INSERT INTO DIRECTOR VALUES (DIRECTOR_NO_SEQ.NEXTVAL, '이노우에 다케히코');