-- 국가

CREATE SEQUENCE COUNTRY_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCYCLE
;

INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '한국');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '미국');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '일본');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '대만');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '영국');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '인도');
INSERT INTO COUNTRY VALUES (COUNTRY_NO_SEQ.NEXTVAL, '프랑스');
