-- 카테고리

CREATE SEQUENCE CONTENTS_CATEGORY_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCYCLE
;

INSERT INTO CATEGORY VALUES (CONTENTS_CATEGORY_NO_SEQ.NEXTVAL, '영화');
INSERT INTO CATEGORY VALUES (CONTENTS_CATEGORY_NO_SEQ.NEXTVAL, '드라마');
INSERT INTO CATEGORY VALUES (CONTENTS_CATEGORY_NO_SEQ.NEXTVAL, '예능');