-- 연습용

SELECT EMP_NAME 이름,
    SUBSTR(EMP_NO,1,6) 주민번호,
    TRUNC(MONTHS_BETWEEN( SYSDATE, TO_DATE( SUBSTR(EMP_NO, 1, 6) ))/12) 나이,
    HIRE_DATE 입사일,
    TRUNC( MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12 ) 근무년수
FROM EMPLOYEE
;

SELECT TRUNC(MONTHS_BETWEEN( SYSDATE, SUBSTR(EMP_NO, 1, 6))/12)
FROM EMPLOYEE
;

SELECT EMP_NAME AS "ENAME 이름",
    SUBSTR(EMP_NO, 1, 6) AS "ENO 주민번호",
    TRUNC(MONTHS_BETWEEN( SYSDATE, SUBSTR(EMP_NO, 1, 6))/12) AS "함수식 나이",
    HIRE_DATE AS "HDATE 입사일",
    TRUNC( MONTHS_BETWEEN( SYSDATE, HIRE_DATE ) / 12 ) AS "함수식 근무년수"
FROM EMPLOYEE
;

SELECT * FROM EMPLOYEE
;
DELETE EMPLOYEE
WHERE EMP_ID = 214
;
SELECT TO_DATE(861015)
FROM DUAL
;

-- 테이블 생성
CREATE TABLE MEMBER (
    ID VARCHAR2(100)
    , PW VARCHAR2(100)
    , NICK VARCHAR2(100)
);

-- MEMBER 테이블 모든 칼럼 조회
SELECT *
FROM MEMBER
;
/*
    <DML>
    INSERT
    UPDATE
    DELETE
*/

INSERT INTO MEMBER(ID, PW, NICK) VALUES('USER01', '1234', 'X_X');
INSERT INTO MEMBER VALUES('USER02', '2345', 'u_u');
INSERT INTO MEMBER(ID, PW) VALUES('USER03', '67890');
INSERT INTO MEMBER(ID, PW, NICK)
            VALUES('USER04', '123456789', '^_^');
INSERT INTO MEMBER(ID, PW, NICK)
            VALUES('USER05', '2222', '@_@');

UPDATE MEMBER
    SET PW = '7777'
;
UPDATE MEMBER
    SET PW = '2222'
    WHERE ID = 'USER02'
;
UPDATE MEMBER
    SET PW = '1234'
    WHERE ID = 'USER03' OR ID = 'USER04'
;

DELETE MEMBER;

DELETE MEMBER
    WHERE ID = 'USER05'
;

DELETE MEMBER
    WHERE NICK IS NULL
;

DROP TABLE MEMBER;